additionalProperties:
  packageName: actinia_openapi_python_client
  packageVersion: 0.0.5
  packageAuthor: Corey White
  packageAuthorEmail: corey.white@openplains.com
  packageLicense: GPL-3.0
  packageDescription: Actinia Core Python Client
  packageUrl: ""
  packageKeywords: ["actinia", "actinia-core", "python", "client", "grassgis", "gis", "grass", "openplains"]
  packageInstallRequires: ["urllib3 >=2.7.0, <=2.7.0", "python-dateutil", "pydantic >= 2", "typing-extensions >= 4.7.1"]
